on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Build
jobs:
  build:
    name: "Package"
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: ./build/package.sh ./ ./dist
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: package
          path: dist

  test:
    name: Test
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: ./tests/run.sh
